### ISSUE TITLE
unbounded number of requests towards CDSE catalog

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-opensearch-client#28]
CDSE process graphs including the one from the integration tests started failing suddenly:

```
Traceback (most recent call last):   File "/opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 1278, in <module>     main(sys.argv)   File "/opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 1013, in main     run_driver()   File "/opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 984, in run_driver     run_job(   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 54, in memory_logging_wrapper     return function(*args, **kwargs)   File "/opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 1077, in run_job     result = ProcessGraphDeserializer.evaluate(process_graph, env=env, do_dry_run=tracer)   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 348, in evaluate     result = convert_node(result_node, env=env)   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 368, in convert_node     process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1470, in apply_process     args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1470, in <dictcomp>     args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 380, in convert_node     return convert_node(processGraph['node'], env=env)   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 368, in convert_node     process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1470, in apply_process     args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1470, in <dictcomp>     args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 380, in convert_node     return convert_node(processGraph['node'], env=env)   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 368, in convert_node     process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1502, in apply_process     return process_function(args=ProcessArgs(args, process_id=process_id), env=env)   File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 546, in load_collection     return env.backend_implementation.catalog.load_collection(collection_id, load_params=load_params, env=env)   File "/opt/openeo/lib/python3.8/site-packages/openeo/util.py", line 393, in wrapper     return f(*args, **kwargs)   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/layercatalog.py", line 123, in load_collection     return self._load_collection_cached(collection_id, load_params, WhiteListEvalEnv(env,WHITELIST))   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/layercatalog.py", line 643, in _load_collection_cached     pyramid = s1_backscatter_orfeo.creodias(   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/collections/s1backscatter_orfeo.py", line 808, in creodias     feature_pyrdd, layer_metadata_py = self._build_feature_rdd(   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/collections/s1backscatter_orfeo.py", line 158, in _build_feature_rdd     feature_pyrdd, layer_metadata_sc = self._load_feature_rdd(   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/collections/s1backscatter_orfeo.py", line 117, in _load_feature_rdd     json_rdd = file_rdd_factory.loadSpatialFeatureJsonRDD(projected_polygons, from_date, to_date, zoom, tile_size,datacubeParams)   File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__   File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value py4j.protocol.Py4JJavaError: An error occurred while calling o1565.loadSpatialFeatureJsonRDD. : java.lang.StackOverflowError         at java.base/java.security.AccessController.doPrivileged(Native Method)         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1170)         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)         at scalaj.http.HttpRequest.closeStreams(Http.scala:444)         at scalaj.http.HttpRequest.doConnection(Http.scala:370)         at scalaj.http.HttpRequest.exec(Http.scala:343)         at scalaj.http.HttpRequest.asString(Http.scala:492)         at org.openeo.opensearch.OpenSearchClient.$anonfun$execute$1(OpenSearchClient.scala:137)         at org.openeo.opensearch.package$.attempt$1(package.scala:42)

**Comment by bossie** [comment]
We're relying on the value of `"itemsPerPage"` in the response to determine whether we should request another page; looks like up until recently this was indeed the number of features in the page, whereas now it (probably correctly) corresponds to the maximum number of features in a page (= `maxRecords` param passed by the client):

"properties": {
"id": "019a16bf-8205-5767-b8f3-f679bdabf4c8",
"totalResults": null,
"exactCount": 0,
"startIndex": 1,
"itemsPerPage": 100,

**Comment by bossie** [comment]
Fixed by looking at the actual number of features in the response instead.

Note that other properties like `totalResults` (null instead of 4) and `exactCount` (used to be a boolean) are b0rked as well.
